---
Name: lightboxconfig
Before: modelascontrollerroutes
---
Director:
  rules:
    'lightbox/$URLSegment': 'LightboxController'
---
Name: lightboxextensions
After: 'cms/*'
---
HtmlEditorField_Toolbar:
  extensions:
    - HtmlEditorField_ToolbarLightboxExtension
HtmlEditorField:
  extensions:
    - HtmlEditorFieldLightboxExtension
SiteTree:
  extensions:
    - DataObjectLightboxExtension